export const LOG_IN = 'LOG_IN';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILED = 'LOG_IN_FAILED';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';

export const LOG_OUT = 'LOG_OUT';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

export const FETCH_INVOICES = 'FETCH_INVOICES';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILED = 'FETCH_FAILED';

export const FETCH_GET_INVOICE = 'FETCH_GET_INVOICE';
export const FETCH_INVOICE_GET_SUCCESS = 'FETCH_INVOICE_GET_SUCCESS';
export const FETCH_INVOICE_GET_FAILED = 'FETCH_INVOICE_GET_FAILED';

export const ADD_INVOICE = 'ADD_INVOICE';
export const ADD_INVOICE_SUCCESS = 'ADD_INVOICE_SUCCESS';
export const ADD_INVOICE_FAILED = 'ADD_INVOICE_FAILED';

export const EDIT_INVOICE = 'EDIT_INVOICE';
export const EDIT_INVOICE_SUCCESS = 'EDIT_INVOICE_SUCCESS';
export const EDIT_INVOICE_FAILED = 'EDIT_INVOICE_FAILED';

export const REMOVE_INVOICE = 'REMOVE_INVOICE';
export const REMOVE_INVOICE_SUCCESS = 'REMOVE_INVOICE_SUCCESS';
export const REMOVE_INVOICE_FAILED = 'REMOVE_INVOICE_FAILED';

export const REMOVE_DETAIL = 'REMOVE_DETAIL';
export const REMOVE_DETAIL_SUCCESS = 'REMOVE_DETAIL_SUCCESS';
export const REMOVE_DETAIL_FAILED = 'REMOVE_DETAIL_FAILED';